import { create } from "zustand";
import { createJSONStorage, persist } from "zustand/middleware";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { InventoryItem } from "../types/cafe";

interface InventoryState {
  items: InventoryItem[];
  addItem: (item: Omit<InventoryItem, "id" | "createdAt" | "updatedAt">) => InventoryItem;
  updateItem: (id: string, updates: Partial<InventoryItem>) => void;
  deleteItem: (id: string) => void;
  getItemById: (id: string) => InventoryItem | undefined;
  getLowStockItems: () => InventoryItem[];
  updateQuantity: (id: string, quantity: number) => void;
  reduceStock: (id: string, amount: number) => boolean;
  initializeSampleData: () => void;
}

export const useInventoryStore = create<InventoryState>()(
  persist(
    (set, get) => ({
      items: [],

      addItem: (item) => {
        const newItem: InventoryItem = {
          ...item,
          id: Date.now().toString(),
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        };
        set((state) => ({ items: [...state.items, newItem] }));
        return newItem;
      },

      updateItem: (id, updates) => {
        set((state) => ({
          items: state.items.map((item) =>
            item.id === id
              ? { ...item, ...updates, updatedAt: new Date().toISOString() }
              : item
          ),
        }));
      },

      deleteItem: (id) => {
        set((state) => ({
          items: state.items.filter((item) => item.id !== id),
        }));
      },

      getItemById: (id) => {
        return get().items.find((item) => item.id === id);
      },

      getLowStockItems: () => {
        return get().items.filter((item) => item.quantity <= item.minQuantity);
      },

      updateQuantity: (id, quantity) => {
        set((state) => ({
          items: state.items.map((item) =>
            item.id === id
              ? {
                  ...item,
                  quantity,
                  lastRestocked: new Date().toISOString(),
                  updatedAt: new Date().toISOString(),
                }
              : item
          ),
        }));
      },

      reduceStock: (id, amount) => {
        const item = get().getItemById(id);
        if (!item || item.quantity < amount) {
          return false;
        }
        get().updateQuantity(id, item.quantity - amount);
        return true;
      },

      initializeSampleData: () => {
        const sampleItems: InventoryItem[] = [
          // COFFEE BEANS & COFFEE INGREDIENTS
          {
            id: "1",
            name: "Coffee Beans (Arabica)",
            category: "Coffee Beans",
            unit: "kg",
            quantity: 25,
            minQuantity: 5,
            costPerUnit: 450,
            supplier: "Philippine Coffee Co.",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "2",
            name: "Whole Milk",
            category: "Dairy",
            unit: "liters",
            quantity: 30,
            minQuantity: 10,
            costPerUnit: 65,
            supplier: "Fresh Dairy Farm",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "3",
            name: "Ice",
            category: "Basics",
            unit: "kg",
            quantity: 50,
            minQuantity: 20,
            costPerUnit: 15,
            supplier: "Ice Factory",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },

          // SYRUPS & FLAVORINGS
          {
            id: "10",
            name: "Vanilla Syrup",
            category: "Syrups",
            unit: "liters",
            quantity: 8,
            minQuantity: 2,
            costPerUnit: 180,
            supplier: "Flavor House",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "11",
            name: "Almond Syrup",
            category: "Syrups",
            unit: "liters",
            quantity: 8,
            minQuantity: 2,
            costPerUnit: 180,
            supplier: "Flavor House",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "12",
            name: "Hazelnut Syrup",
            category: "Syrups",
            unit: "liters",
            quantity: 8,
            minQuantity: 2,
            costPerUnit: 180,
            supplier: "Flavor House",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "13",
            name: "Chocolate Syrup",
            category: "Syrups",
            unit: "liters",
            quantity: 10,
            minQuantity: 3,
            costPerUnit: 160,
            supplier: "Flavor House",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "14",
            name: "Caramel Syrup",
            category: "Syrups",
            unit: "liters",
            quantity: 8,
            minQuantity: 2,
            costPerUnit: 180,
            supplier: "Flavor House",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "15",
            name: "Strawberry Syrup",
            category: "Syrups",
            unit: "liters",
            quantity: 8,
            minQuantity: 2,
            costPerUnit: 180,
            supplier: "Flavor House",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },

          // WAFFLE INGREDIENTS
          {
            id: "20",
            name: "Waffle Mix",
            category: "Waffle Ingredients",
            unit: "kg",
            quantity: 15,
            minQuantity: 5,
            costPerUnit: 120,
            supplier: "Baking Essentials",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "21",
            name: "Eggs",
            category: "Basics",
            unit: "trays",
            quantity: 10,
            minQuantity: 3,
            costPerUnit: 180,
            supplier: "Farm Fresh",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "22",
            name: "Butter",
            category: "Dairy",
            unit: "kg",
            quantity: 5,
            minQuantity: 2,
            costPerUnit: 250,
            supplier: "Fresh Dairy Farm",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "23",
            name: "Fresh Strawberries",
            category: "Fresh Fruits",
            unit: "kg",
            quantity: 8,
            minQuantity: 2,
            costPerUnit: 220,
            supplier: "Baguio Farms",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "24",
            name: "Whipped Cream",
            category: "Toppings",
            unit: "cans",
            quantity: 12,
            minQuantity: 4,
            costPerUnit: 95,
            supplier: "Dairy Supplies",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },

          // SODA & BEVERAGE INGREDIENTS
          {
            id: "30",
            name: "Soda Water / Sparkling Water",
            category: "Beverages",
            unit: "liters",
            quantity: 40,
            minQuantity: 15,
            costPerUnit: 25,
            supplier: "Beverage Distributors",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "31",
            name: "Green Apple Syrup",
            category: "Syrups",
            unit: "liters",
            quantity: 6,
            minQuantity: 2,
            costPerUnit: 190,
            supplier: "Flavor House",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "32",
            name: "Blueberry Syrup",
            category: "Syrups",
            unit: "liters",
            quantity: 6,
            minQuantity: 2,
            costPerUnit: 190,
            supplier: "Flavor House",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "33",
            name: "Lychee Syrup",
            category: "Syrups",
            unit: "liters",
            quantity: 6,
            minQuantity: 2,
            costPerUnit: 190,
            supplier: "Flavor House",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "34",
            name: "Fresh Lemons",
            category: "Fresh Fruits",
            unit: "kg",
            quantity: 10,
            minQuantity: 3,
            costPerUnit: 150,
            supplier: "Fruit Market",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "35",
            name: "Cucumber",
            category: "Fresh Vegetables",
            unit: "kg",
            quantity: 8,
            minQuantity: 2,
            costPerUnit: 80,
            supplier: "Vegetable Supplier",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "36",
            name: "Yakult",
            category: "Beverages",
            unit: "packs",
            quantity: 20,
            minQuantity: 5,
            costPerUnit: 55,
            supplier: "Yakult Distributor",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "37",
            name: "Sugar",
            category: "Basics",
            unit: "kg",
            quantity: 20,
            minQuantity: 5,
            costPerUnit: 60,
            supplier: "General Supplies",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },

          // SNACK INGREDIENTS
          {
            id: "40",
            name: "Siopao (Frozen)",
            category: "Frozen Foods",
            unit: "pieces",
            quantity: 100,
            minQuantity: 30,
            costPerUnit: 18,
            supplier: "Dimsum Factory",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "41",
            name: "Hotdog",
            category: "Meats",
            unit: "kg",
            quantity: 15,
            minQuantity: 5,
            costPerUnit: 180,
            supplier: "Meat Supplier",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "42",
            name: "Hotdog Buns",
            category: "Bakery",
            unit: "packs",
            quantity: 20,
            minQuantity: 8,
            costPerUnit: 45,
            supplier: "Bakery Supplier",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "43",
            name: "Cheese Slices",
            category: "Dairy",
            unit: "packs",
            quantity: 10,
            minQuantity: 3,
            costPerUnit: 120,
            supplier: "Dairy Supplies",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "44",
            name: "Bacon",
            category: "Meats",
            unit: "kg",
            quantity: 8,
            minQuantity: 2,
            costPerUnit: 320,
            supplier: "Meat Supplier",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "45",
            name: "Mayonnaise",
            category: "Condiments",
            unit: "kg",
            quantity: 5,
            minQuantity: 2,
            costPerUnit: 150,
            supplier: "General Supplies",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "46",
            name: "Mustard",
            category: "Condiments",
            unit: "bottles",
            quantity: 8,
            minQuantity: 2,
            costPerUnit: 85,
            supplier: "General Supplies",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "47",
            name: "Chicken Poppers (Frozen)",
            category: "Frozen Foods",
            unit: "kg",
            quantity: 12,
            minQuantity: 4,
            costPerUnit: 280,
            supplier: "Frozen Foods Supplier",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "48",
            name: "Chicken Fillet (Frozen)",
            category: "Frozen Foods",
            unit: "kg",
            quantity: 12,
            minQuantity: 4,
            costPerUnit: 290,
            supplier: "Frozen Foods Supplier",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "49",
            name: "Siomai (Frozen)",
            category: "Frozen Foods",
            unit: "pieces",
            quantity: 200,
            minQuantity: 50,
            costPerUnit: 4,
            supplier: "Dimsum Factory",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "50",
            name: "Shanghai Rolls (Frozen)",
            category: "Frozen Foods",
            unit: "pieces",
            quantity: 150,
            minQuantity: 40,
            costPerUnit: 6,
            supplier: "Dimsum Factory",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "51",
            name: "Potato Fries (Frozen)",
            category: "Frozen Foods",
            unit: "kg",
            quantity: 20,
            minQuantity: 8,
            costPerUnit: 140,
            supplier: "Frozen Foods Supplier",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "52",
            name: "Cooking Oil",
            category: "Basics",
            unit: "liters",
            quantity: 15,
            minQuantity: 5,
            costPerUnit: 85,
            supplier: "General Supplies",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },

          // RICE MEAL INGREDIENTS
          {
            id: "60",
            name: "Rice",
            category: "Basics",
            unit: "kg",
            quantity: 50,
            minQuantity: 15,
            costPerUnit: 55,
            supplier: "Rice Supplier",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "61",
            name: "Spam",
            category: "Canned Goods",
            unit: "cans",
            quantity: 30,
            minQuantity: 10,
            costPerUnit: 95,
            supplier: "General Supplies",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "62",
            name: "Sausage",
            category: "Meats",
            unit: "kg",
            quantity: 10,
            minQuantity: 3,
            costPerUnit: 240,
            supplier: "Meat Supplier",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "63",
            name: "Tocino (Sweet Pork)",
            category: "Meats",
            unit: "kg",
            quantity: 10,
            minQuantity: 3,
            costPerUnit: 260,
            supplier: "Meat Supplier",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "64",
            name: "Longanisa",
            category: "Meats",
            unit: "kg",
            quantity: 10,
            minQuantity: 3,
            costPerUnit: 270,
            supplier: "Meat Supplier",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "65",
            name: "Garlic",
            category: "Fresh Vegetables",
            unit: "kg",
            quantity: 3,
            minQuantity: 1,
            costPerUnit: 120,
            supplier: "Vegetable Supplier",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "66",
            name: "Soy Sauce",
            category: "Condiments",
            unit: "liters",
            quantity: 5,
            minQuantity: 2,
            costPerUnit: 75,
            supplier: "General Supplies",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "67",
            name: "Vinegar",
            category: "Condiments",
            unit: "liters",
            quantity: 5,
            minQuantity: 2,
            costPerUnit: 45,
            supplier: "General Supplies",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },

          // PACKAGING & DISPOSABLES
          {
            id: "70",
            name: "22oz Cups (Cold)",
            category: "Packaging",
            unit: "pieces",
            quantity: 500,
            minQuantity: 100,
            costPerUnit: 3.5,
            supplier: "Packaging Supplier",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "71",
            name: "Plastic Straws",
            category: "Packaging",
            unit: "pieces",
            quantity: 800,
            minQuantity: 200,
            costPerUnit: 0.5,
            supplier: "Packaging Supplier",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "72",
            name: "Plastic Lids",
            category: "Packaging",
            unit: "pieces",
            quantity: 500,
            minQuantity: 100,
            costPerUnit: 2.5,
            supplier: "Packaging Supplier",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "73",
            name: "Takeout Boxes",
            category: "Packaging",
            unit: "pieces",
            quantity: 300,
            minQuantity: 80,
            costPerUnit: 8,
            supplier: "Packaging Supplier",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "74",
            name: "Napkins",
            category: "Packaging",
            unit: "packs",
            quantity: 30,
            minQuantity: 10,
            costPerUnit: 45,
            supplier: "Packaging Supplier",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "75",
            name: "Plastic Forks",
            category: "Packaging",
            unit: "pieces",
            quantity: 500,
            minQuantity: 150,
            costPerUnit: 0.8,
            supplier: "Packaging Supplier",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "76",
            name: "Plastic Spoons",
            category: "Packaging",
            unit: "pieces",
            quantity: 500,
            minQuantity: 150,
            costPerUnit: 0.8,
            supplier: "Packaging Supplier",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },

          // SEASONINGS & TOPPINGS
          {
            id: "80",
            name: "Salt",
            category: "Seasonings",
            unit: "kg",
            quantity: 5,
            minQuantity: 2,
            costPerUnit: 30,
            supplier: "General Supplies",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "81",
            name: "Black Pepper",
            category: "Seasonings",
            unit: "kg",
            quantity: 2,
            minQuantity: 0.5,
            costPerUnit: 180,
            supplier: "General Supplies",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "82",
            name: "Cajun Seasoning",
            category: "Seasonings",
            unit: "kg",
            quantity: 2,
            minQuantity: 0.5,
            costPerUnit: 220,
            supplier: "Spice Supplier",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "83",
            name: "Sea Salt (Coarse)",
            category: "Seasonings",
            unit: "kg",
            quantity: 3,
            minQuantity: 1,
            costPerUnit: 85,
            supplier: "General Supplies",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "84",
            name: "Ketchup",
            category: "Condiments",
            unit: "bottles",
            quantity: 10,
            minQuantity: 3,
            costPerUnit: 65,
            supplier: "General Supplies",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "85",
            name: "Chili Sauce",
            category: "Condiments",
            unit: "bottles",
            quantity: 8,
            minQuantity: 2,
            costPerUnit: 75,
            supplier: "General Supplies",
            lastRestocked: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
        ];
        set({ items: sampleItems });
      },
    }),
    {
      name: "inventory-storage",
      storage: createJSONStorage(() => AsyncStorage),
    }
  )
);
